# Generated by Django 5.0.6 on 2024-07-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_artworkgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkgallery',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
